#!/bin/bash

PREFIX="git@github.com:gnustep/"
FILES="libobjc2 libs-base tools-make libs-xcode tools-buildtool "

for file in ${FILES}
do
    GITURL=${PREFIX}${file}
    if
	test -d ${file}
    then
        cd $file
        git pull ${GITURL} master
	cd ..
    else
	git clone --recursive ${GITURL}
    fi
done

exit 0
